Pptx python service
GayashanSameera/PPTX-serverless pull request #12
Opened 2022-08-05 12:03 UTC by tharukshi1bt

2022-08-08 04:50 UTC, GayashanSameera approved these changes

2022-08-09 10:34 UTC, thivankanimesh1bt requested changes

2022-08-09 10:34 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +                expression = Expression(Tag)
Don't pass Tag class as an argument. Use methods in the Tag class by using inheritance in the Expression class.

2022-08-11 01:32 UTC, thivankanimesh1bt approved these changes

2022-08-12 04:07 UTC, GayashanSameera approved these changes

2022-08-12 04:08 UTC, merged