added toc sub heading changes
GayashanSameera/PPTX-serverless pull request #20
Opened 2022-08-18 11:51 UTC by hacSandamali

2022-08-18 17:24 UTC, thivankanimesh1bt requested changes

2022-08-18 17:24 UTC, thivankanimesh1bt commented on pptx_generator/tpip_pptx/toc.py
> +            if sub != None:
What happens if an empty sub list is provided? Please handle empty sub list checking also.

2022-08-19 07:14 UTC, thivankanimesh1bt approved these changes

2022-08-19 09:25 UTC, tharukshi1bt approved these changes

2022-08-19 09:26 UTC, merged