remove tables negative side handling
GayashanSameera/PPTX-serverless pull request #28
Opened 2022-09-06 06:47 UTC by tharukshi1bt

2022-09-06 07:04 UTC, thivankanimesh1bt requested changes

2022-09-06 07:04 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +                except ClientError as e:
Check the specific exception type and then send the error response according to that. (ex: if the exception type is "bucket not found" then send "destination bucket cannot be found" response message).

Handle every possible exceptions in every places in the handler function.

2022-09-06 07:04 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +            return False
Handle error response message properly.

2022-09-06 07:04 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +         response= {
Handle error response message based on the exception type.

2022-09-06 08:51 UTC, thivankanimesh1bt requested changes

2022-09-06 08:51 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +                except ClientError as e:
pending...

2022-09-06 08:51 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +            return False
pending...

2022-09-06 08:51 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +         response= {
pending...

2022-09-07 03:32 UTC, thivankanimesh1bt approved these changes

2022-09-12 06:30 UTC, GayashanSameera approved these changes

2022-09-12 06:47 UTC, thivankanimesh1bt requested changes

2022-09-12 06:47 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +        f = open('/tmp/demo1.pptx', "wb")
Why demo1.pptx is hardcoded?

2022-09-12 06:47 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +        response = s3_client.get_object(Bucket=POC_PPTX_BUCKET, Key='demo1.pptx')
why demo1.pptx is hardcoded?

2022-09-12 06:47 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +        presentation_object = Presentation('/tmp/demo1.pptx')
Dont hardcode demo.pptx

2022-09-12 06:47 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +        subprocess.call('dir && ppt2pdf file demo1.pptx', shell=True, cwd='/tmp')
dont hardcode demo1.pptx

2022-09-12 06:51 UTC, thivankanimesh1bt requested changes

2022-09-12 06:51 UTC, thivankanimesh1bt commented on pptx_generator/src/handlers/generate_pptx.py
> +            res.append(path)
What is the purpose of this 'res' list?

2022-09-12 07:01 UTC, thivankanimesh1bt approved these changes

2022-09-12 07:19 UTC, merged